<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsToml" Version="1.*" />
        <PackageReference Include="Danom" Version="2.*" />
        <PackageReference Include="Markdig" Version="0.*" />
        <PackageReference Include="Scriban" Version="6.*" />
        <InternalsVisibleTo Include="Ditto.Tests" />
    </ItemGroup>
</Project>
